let server_base = 'http://10.2.47.17:9888'
// let server_base = 'http://localhost:9888'
export let g_server_sites_url = server_base + '/sites'
export let g_server_site_url = server_base + '/site/'
export let g_server_update_version_url = server_base + '/update_version'